version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      # Workflows in .github/workflows.
      - /
      # Composite actions.
      - /.github/actions/setup-tlaplus
    schedule:
      interval: weekly
