(* ===== Names reserved by the emitted TLA+ module =====

   A leaf module shared by the front end (Check_scope, Alpha_convert) and
   the back end (Emit_tla): the emitter's generated top-level names and the
   operators of the standard modules it EXTENDS are data both sides need,
   and keeping them here lets the front end reject collisions without
   depending on the emitter. *)

(* Null sentinel for not-yet-assigned frame fields. A CONSTANT that the
   generated .cfg assigns a model value (following PlusCal's convention):
   model values compare unequal to every other value without a TLC type
   error. A string sentinel would crash TLC's liveness checking, which
   compares states for equality — and a frame field that holds "__null__"
   in one state and an int in another is exactly such a comparison. *)
let default_init_value = "defaultInitValue"

(* Top-level TLA+ names the emitter generates, plus the operators of the
   standard modules it EXTENDS (TLC, Sequences, Integers, and conditionally
   FiniteSets). User module-level names are passed through verbatim, so a
   collision produces a multiply-defined symbol at SANY — or, for
   [default_init_value], silently aliases the null frame sentinel.
   Check_scope rejects module-level declarations of these. *)
let module_names =
  [
    (* generated by the emitter *)
    "pc";
    "stack";
    "vars";
    "ProcSet";
    "Init";
    "Next";
    "Spec";
    "Terminating";
    "Termination";
    default_init_value;
    (* Integers / Naturals *)
    "Nat";
    "Int";
    (* Sequences *)
    "Seq";
    "Len";
    "Head";
    "Tail";
    "Append";
    "SubSeq";
    "SelectSeq";
    (* TLC *)
    "Print";
    "PrintT";
    "Assert";
    "JavaTime";
    "TLCGet";
    "TLCSet";
    "Permutations";
    "SortSeq";
    "RandomElement";
    "Any";
    "ToString";
    "TLCEval";
    (* FiniteSets *)
    "IsFiniteSet";
    "Cardinality";
  ]

(* Action labels ("L" ^ counter, see Linearize.fresh_label) are emitted as
   top-level operators alongside user definitions, so names of that shape
   are reserved as well. *)
let is_generated_action_label name =
  String.length name >= 2
  && name.[0] = 'L'
  && String.for_all
       (fun c -> '0' <= c && c <= '9')
       (String.sub name 1 (String.length name - 1))

let is_reserved name =
  List.mem name module_names || is_generated_action_label name
