name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.2.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@fefd9c240b9d934d5d25aa9c2a8caae6c7b40079 # v3.6.0
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: opam install . --deps-only --with-test

      - name: Set up TLA+
        uses: ./.github/actions/setup-tlaplus
        id: tlaplus

      - name: Run tests
        run: opam exec -- dune runtest
        env:
          SANPOU_JAVA: ${{ steps.tlaplus.outputs.java-path }}
          SANPOU_TLA2TOOLS_JAR: ${{ steps.tlaplus.outputs.tla2tools-jar }}

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.2.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@fefd9c240b9d934d5d25aa9c2a8caae6c7b40079 # v3.6.0
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build
